baseURL = "https://www.parthrabari.in/"
languageCode = "en-us"
title = "A rom"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

  [params]
  avatar = "profile.JPG"
  author = "Parth rabari"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

  [params.social]
  Github        = "parthrabari"
  Email         = "cron@parthrabari.in"
  Twitter       = "rabari_parth"
  
  ## Main Menu
[[menu.main]]
  name = "blog"
  weight = 1
  identifier = "blog"
  url = "/blog/"
